### ISSUE TITLE
extract_image_feature generates "nan" probability

### ISSUE THREAD

**Issue by hytseng0509** [ColumbiaDVMM/CDC#13]
Hi,

Thanks for sharing the codes.
I followed the steps of reproducing results on THUMOS14. However, I found that some probabilities in .prob file generated by executing ./xfeat.sh were "nan". (not all probabilities in a single .prob file is "nan", only a few of them)
Any idea what may be wrong?

Thanks!

**Comment by sunnyxiaohu** [comment]
How about you batch_size ? Just decrease your batch_size when testing.

**Comment by hytseng0509** [comment]
My batch_size is 4, and the number of mini-batch is 9046, as suggested in the official sample code.

**Comment by minhtriet** [comment]
Why should decreasing batch_size help?

**Comment by sunnyxiaohu** [comment]
It may caused by the implementation of the caffe branch. Try it again, if you still get "nan" probability

**Comment by minhtriet** [comment]
That is actually right, thank you. In my case, I decreased the batch_size from 4 to 1. mini_batch is still 9046.

I think theoretically, the bigger the `batch` number is, the longer the fraction of video is, then hopefully the more accurate the network is able to classify the action. Will do some experiment to see which batch_size produce best result.

One more thing, could you elaborate more why do you think it may caused by the implementation of the caffe branch?

**Comment by zhengshou** [comment]
Hi,

Thank you for your interest. This issue seems due to a bug in C3D. I have fixed and updated it.

Best,
Zheng
