### ISSUE TITLE
 there is no file 'probcrf.mat' when I am trying to  run step3_gen_CDC_det.m

### ISSUE THREAD

**Issue by zhangxgu** [ColumbiaDVMM/CDC#3]
In line 5 of step3_gen_CDC_det.m, there is no file 'probcrf.mat' after I have run all the codes as you write in **Reproduce results on THUMOS 2014 dataset**
Thanks!

**Comment by zhangxgu** [comment]
And there is another question:
In **CDC network prediction**, you should change line 9 in gen_test_bin_and_list.py from 
**listfile = open(outputdir+"test.lst",'w')** to **listfile = open(outputdir+"example.test.lst",'w')**.


Otherwise next step will read older example.test.lst and cannot read new datasets test.lst.

**Comment by bityangke** [comment]
I am not the author.
I used "proball.mat" instead of "proballcrf.mat".
proballcrf.mat might be prob postprocessed by CRF.
I wonder if crf will help improve the results.

**Comment by zhangxgu** [comment]
@bityangke Thanks!
I find this really works. : )

**Comment by zhangxgu** [comment]
@bityangke excuse me but there is another question that after I run ./xfeat.sh in **Reproduce results on THUMOS 2014 dataset** , there is no file /feat/ in 'cdc\THUMOS14\test'. Is this xfeat.sh lack of some thing? 

@zhengshou

**Comment by bityangke** [comment]
Sorry, I do not run this experiments.
I just use proball.mat to generate some results for my comparison experiments.

**Comment by zhengshou** [comment]
Thanks @bityangke and @zhangxgu for the heads-up.

Yes it is typo. It should be "proball.mat" rather than "probcrf.mat". Fixed now. Previously I tried crf but it does not help.

example.test.lst is just an example of test list file which will be generated by gen_test_bin_and_list.py rather than read by gen_test_bin_and_list.py

You need to prepare that ./feat/ folder by yourself according to your prefix file.
