### ISSUE TITLE
The FFmpeg version you used to extract frames?

### ISSUE THREAD

**Issue by yangchihyuan** [ColumbiaDVMM/CDC#7]
Hello Zheng,

Could you help let me know your FFmpeg version used to extract frames from the THUMOS14 data set? I got a problem that although I use your command to extract frames in the scnn/run_demo.m
cmd = ['../lib/preprocess/ffmpeg -i ' videodir videoname '.' videotype ' -r ' num2str(framerate) ...     ' -f image2 ' framedir videoname '/' '%06d.jpg 2>' framedir 'frame_extract.log'];
, the number extracted is 1 frame less than the yours for some videos. For example, I got only 845 frames from the test_video_0000004.mp4, but yours is 846, according to the filename 000815.bin belonging to the 0000004 video in the prefix.lst file.
As a result, I got an error while running the compute_framelevel_mAP.m because the length of label_test in the 'multi-label-test.mat is different from my prob length (label_test: 1154579 vs prob: 1154473).
I am wondering the problem of fewer extracted frames is caused by different FFmpeg versions. Mine is 3.3.3-1ubuntu1~16.04.york and what is yours?

Best regards,

**Comment by zhengshou** [comment]
Few frames more or less during frame extraction won't affect the final results. You can construct your own frame-level ground truth file to measure your performances based on your extracted frames. Also, note that seems using ffmpeg to extract jpg sometimes suffers from information loss due to compression and it is better to extract png format image.
